# Dockerfile.frontend
FROM node:20 as builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

FROM node:20

WORKDIR /app

COPY --from=builder /app/build ./

EXPOSE 3000

CMD ["npm", "start"]
