version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend  # Specify the Dockerfile for backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - PORT=5000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend  # Specify the Dockerfile for frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:5000
  mongo:
    image: mongo
    ports:
      - "27017:27017"
